[package]
name = "natoalpha"
version = "0.1.0"
authors = ["James Magahern <james@magahern.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "*"
lazy_static = "1.4.0"
termion = "*"
rand = "0.7.3"

